import type { Achievement } from '../types';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-sessions-10',
    label: 'Guerrier',
    description: 'Complète 10 séances',
    emoji: '⚔️',
    target: 10,
    type: 'totalSessions',
    reward: 'oldPassChest',
  },
  {
    id: 'ach-sessions-50',
    label: 'Vétéran',
    description: 'Complète 50 séances',
    emoji: '🎖️',
    target: 50,
    type: 'totalSessions',
    reward: 'oldPassChest',
  },
  {
    id: 'ach-sessions-100',
    label: 'Centurion',
    description: 'Complète 100 séances',
    emoji: '🏛️',
    target: 100,
    type: 'totalSessions',
    reward: 'guaranteedEpique',
  },
  {
    id: 'ach-reps-1000',
    label: 'Machine à reps',
    description: 'Fais 1 000 reps au total',
    emoji: '🔧',
    target: 1000,
    type: 'totalReps',
    reward: 'oldPassChest',
  },
  {
    id: 'ach-reps-5000',
    label: 'Infatigable',
    description: 'Fais 5 000 reps au total',
    emoji: '🔥',
    target: 5000,
    type: 'totalReps',
    reward: 'oldPassChest',
  },
  {
    id: 'ach-reps-10000',
    label: 'Légende vivante',
    description: 'Fais 10 000 reps au total',
    emoji: '👑',
    target: 10000,
    type: 'totalReps',
    reward: 'guaranteedLegendaire',
  },
  {
    id: 'ach-duration-5h',
    label: 'Marathonien',
    description: '5 heures d\'entraînement au total',
    emoji: '🏃',
    target: 18000,
    type: 'totalDuration',
    reward: 'oldPassChest',
  },
  {
    id: 'ach-duration-20h',
    label: 'Acharné',
    description: '20 heures d\'entraînement au total',
    emoji: '⏱️',
    target: 72000,
    type: 'totalDuration',
    reward: 'guaranteedEpique',
  },
  {
    id: 'ach-amrap-5',
    label: 'AMRAP Warrior',
    description: 'Complète 5 séances AMRAP',
    emoji: '💀',
    target: 5,
    type: 'totalAmrap',
    reward: 'oldPassChest',
  },
  {
    id: 'ach-amrap-20',
    label: 'AMRAP Demon',
    description: 'Complète 20 séances AMRAP',
    emoji: '😈',
    target: 20,
    type: 'totalAmrap',
    reward: 'guaranteedEpique',
  },
  {
    id: 'ach-variety-10',
    label: 'Polyvalent',
    description: 'Utilise 10 exercices différents',
    emoji: '🎯',
    target: 10,
    type: 'exerciseVariety',
    reward: 'oldPassChest',
  },
  {
    id: 'ach-variety-20',
    label: 'Complet',
    description: 'Utilise 20 exercices différents',
    emoji: '🌟',
    target: 20,
    type: 'exerciseVariety',
    reward: 'oldPassChest',
  },
  {
    id: 'ach-sets-100',
    label: 'Sérieur',
    description: 'Complète 100 séries',
    emoji: '📊',
    target: 100,
    type: 'totalSets',
    reward: 'oldPassChest',
  },
  {
    id: 'ach-sets-500',
    label: 'Sérieur fou',
    description: 'Complète 500 séries',
    emoji: '📈',
    target: 500,
    type: 'totalSets',
    reward: 'guaranteedEpique',
  },
];
