import type { Exercise } from '../types';

export const DEFAULT_EXERCISES: Exercise[] = [
  { id: 'pull-ups', name: 'Tractions', category: 'pull', canBeWeighted: true },
  { id: 'chin-ups', name: 'Chin-ups', category: 'pull', canBeWeighted: true },
  { id: 'muscle-ups', name: 'Muscle-ups', category: 'pull', canBeWeighted: true },
  { id: 'australian-rows', name: 'Rowings australiens', category: 'pull', canBeWeighted: true },
  { id: 'rowing-barre', name: 'Rowing barre', category: 'pull', canBeWeighted: true },
  { id: 'rowing-haltere', name: 'Rowing haltère', category: 'pull', canBeWeighted: true },
  { id: 'curl-biceps', name: 'Curl biceps', category: 'pull', canBeWeighted: true },
  { id: 'curl-marteau', name: 'Curl marteau', category: 'pull', canBeWeighted: true },
  { id: 'oiseau', name: 'Oiseau', category: 'pull', canBeWeighted: true },
  { id: 'shrugs', name: 'Shrugs', category: 'pull', canBeWeighted: true },
  { id: 'pull-over', name: 'Pull-over', category: 'pull', canBeWeighted: true },
  { id: 'dips', name: 'Dips', category: 'push', canBeWeighted: true },
  { id: 'push-ups', name: 'Pompes', category: 'push', canBeWeighted: true },
  { id: 'diamond-push-ups', name: 'Pompes diamant', category: 'push', canBeWeighted: true },
  { id: 'pike-push-ups', name: 'Pike push-ups', category: 'push', canBeWeighted: true },
  { id: 'handstand-push-ups', name: 'HSPU', category: 'push', canBeWeighted: true },
  { id: 'developpe-couche', name: 'Développé couché', category: 'push', canBeWeighted: true },
  { id: 'developpe-incline', name: 'Développé incliné', category: 'push', canBeWeighted: true },
  { id: 'developpe-decline', name: 'Développé décliné', category: 'push', canBeWeighted: true },
  { id: 'developpe-militaire', name: 'Développé militaire', category: 'push', canBeWeighted: true },
  { id: 'extension-triceps', name: 'Extension triceps', category: 'push', canBeWeighted: true },
  { id: 'barre-au-front', name: 'Barre au front', category: 'push', canBeWeighted: true },
  { id: 'elevations-laterales', name: 'Élévations latérales', category: 'push', canBeWeighted: true },
  { id: 'elevations-frontales', name: 'Élévations frontales', category: 'push', canBeWeighted: true },
  { id: 'pistol-squats', name: 'Pistol squats', category: 'legs', canBeWeighted: true },
  { id: 'squats', name: 'Squats', category: 'legs', canBeWeighted: true },
  { id: 'lunges', name: 'Fentes', category: 'legs', canBeWeighted: true },
  { id: 'calf-raises', name: 'Mollets debout', category: 'legs', canBeWeighted: true },
  { id: 'souleve-de-terre', name: 'Soulevé de terre', category: 'legs', canBeWeighted: true },
  { id: 'souleve-de-terre-roumain', name: 'Soulevé de terre roumain', category: 'legs', canBeWeighted: true },
  { id: 'hip-thrust', name: 'Hip thrust', category: 'legs', canBeWeighted: true },
  { id: 'l-sit', name: 'L-sit', category: 'core', canBeWeighted: true, defaultUnit: 'seconds' },
  { id: 'leg-raises', name: 'Relevés de jambes', category: 'core', canBeWeighted: true },
  { id: 'dragon-flags', name: 'Dragon flags', category: 'core', canBeWeighted: true },
  { id: 'crunch', name: 'Crunch', category: 'core', canBeWeighted: true },
  { id: 'gainage', name: 'Gainage', category: 'core', defaultUnit: 'seconds' },
  { id: 'planche', name: 'Planche', category: 'skill', canBeWeighted: true, defaultUnit: 'seconds' },
  { id: 'front-lever', name: 'Front lever', category: 'skill', canBeWeighted: true, defaultUnit: 'seconds' },
  { id: 'back-lever', name: 'Back lever', category: 'skill', canBeWeighted: true, defaultUnit: 'seconds' },
  { id: 'human-flag', name: 'Human flag', category: 'skill', canBeWeighted: true, defaultUnit: 'seconds' },
  // Haltérophilie
  { id: 'clean', name: 'Épaulé', category: 'crossfit', canBeWeighted: true },
  { id: 'power-clean', name: 'Power clean', category: 'crossfit', canBeWeighted: true },
  { id: 'clean-and-jerk', name: 'Épaulé-jeté', category: 'crossfit', canBeWeighted: true },
  { id: 'snatch', name: 'Arraché', category: 'crossfit', canBeWeighted: true },
  { id: 'thruster', name: 'Thruster', category: 'crossfit', canBeWeighted: true },
  { id: 'front-squat', name: 'Front squat', category: 'crossfit', canBeWeighted: true },
  { id: 'overhead-squat', name: 'Overhead squat', category: 'crossfit', canBeWeighted: true },
  { id: 'push-press', name: 'Push press', category: 'crossfit', canBeWeighted: true },
  { id: 'push-jerk', name: 'Push jerk', category: 'crossfit', canBeWeighted: true },
  // Gymnastique
  { id: 'toes-to-bar', name: 'Pointes aux barres', category: 'crossfit', canBeWeighted: true },
  { id: 'chest-to-bar', name: 'Chest to bar', category: 'crossfit', canBeWeighted: true },
  { id: 'bar-muscle-up', name: 'Bar muscle-up', category: 'crossfit', canBeWeighted: true },
  { id: 'ring-muscle-up', name: 'Muscle-up aux anneaux', category: 'crossfit', canBeWeighted: true },
  { id: 'ring-dips', name: 'Dips aux anneaux', category: 'crossfit', canBeWeighted: true },
  { id: 'ghd-sit-ups', name: 'GHD sit-ups', category: 'crossfit', canBeWeighted: true },
  { id: 'wall-walk', name: 'Wall walk', category: 'crossfit' },
  { id: 'handstand-walk', name: 'Marche en ATR', category: 'crossfit', defaultUnit: 'seconds' },
  { id: 'rope-climb', name: 'Montée de corde', category: 'crossfit' },
  // Conditionnement
  { id: 'burpees', name: 'Burpees', category: 'crossfit' },
  { id: 'burpee-box-jump-over', name: 'Burpee box jump over', category: 'crossfit' },
  { id: 'box-jumps', name: 'Box jumps', category: 'crossfit' },
  { id: 'wall-balls', name: 'Wall balls', category: 'crossfit', canBeWeighted: true },
  { id: 'double-unders', name: 'Double unders', category: 'crossfit' },
  { id: 'kettlebell-swing', name: 'Kettlebell swing', category: 'crossfit', canBeWeighted: true },
  { id: 'goblet-squat', name: 'Goblet squat', category: 'crossfit', canBeWeighted: true },
  { id: 'turkish-get-up', name: 'Turkish get-up', category: 'crossfit', canBeWeighted: true },
  { id: 'dumbbell-snatch', name: 'Arraché haltère', category: 'crossfit', canBeWeighted: true },
  { id: 'farmers-walk', name: "Farmer's walk", category: 'crossfit', canBeWeighted: true, defaultUnit: 'seconds' },
  { id: 'sled-push', name: 'Poussée de traîneau', category: 'crossfit', canBeWeighted: true, defaultUnit: 'seconds' },
  // Machines : mesurées au temps, l'app n'a pas de champ mètres hors running.
  { id: 'rameur', name: 'Rameur', category: 'crossfit', defaultUnit: 'seconds' },
  { id: 'assault-bike', name: 'Assault bike', category: 'crossfit', defaultUnit: 'seconds' },
  { id: 'running', name: 'Course', category: 'running' },
  { id: 'sprint', name: 'Sprint', category: 'running' },
  { id: 'interval-run', name: 'Fractionné', category: 'running' },
  { id: 'hill-run', name: 'Course en côte', category: 'running' },
  { id: 'tempo-run', name: 'Tempo run', category: 'running' },
  { id: 'fast-walk', name: 'Marche rapide', category: 'running' },
  { id: 'velo-route', name: 'Vélo route', category: 'velo' },
  { id: 'vtt', name: 'VTT', category: 'velo' },
  { id: 'gravel', name: 'Gravel', category: 'velo' },
  { id: 'velo-ville', name: 'Vélo de ville', category: 'velo' },
  { id: 'home-trainer', name: 'Home trainer', category: 'velo' },
  { id: 'velo-appartement', name: "Vélo d'appartement", category: 'velo' },
  { id: 'spinning', name: 'Spinning', category: 'velo' },
  { id: 'fractionne-velo', name: 'Fractionné vélo', category: 'velo' },
  { id: 'velo-cote', name: 'Vélo en côte', category: 'velo' },
  { id: 'football', name: 'Football', category: 'sportco' },
  { id: 'basketball', name: 'Basketball', category: 'sportco' },
  { id: 'handball', name: 'Handball', category: 'sportco' },
  { id: 'volleyball', name: 'Volleyball', category: 'sportco' },
  { id: 'rugby', name: 'Rugby', category: 'sportco' },
  { id: 'tennis', name: 'Tennis', category: 'sportco' },
  { id: 'padel', name: 'Padel', category: 'sportco' },
  { id: 'badminton', name: 'Badminton', category: 'sportco' },
  { id: 'ping-pong', name: 'Ping-pong', category: 'sportco' },
  { id: 'futsal', name: 'Futsal', category: 'sportco' },
  { id: 'water-polo', name: 'Water-polo', category: 'sportco' },
  { id: 'hockey', name: 'Hockey', category: 'sportco' },
  { id: 'ultimate', name: 'Ultimate', category: 'sportco' },
  { id: 'squash', name: 'Squash', category: 'sportco' },
  { id: 'autre-sport-co', name: 'Autre sport co', category: 'sportco' },
];

export const CATEGORY_LABELS: Record<Exercise['category'], string> = {
  push: 'Poussée',
  pull: 'Tirage',
  legs: 'Jambes',
  core: 'Abdos',
  skill: 'Skills',
  crossfit: 'CrossFit',
  running: 'Running',
  velo: 'Vélo',
  sportco: 'Sport Co',
};
