import type { Exercise } from '../types';

export const DEFAULT_EXERCISES: Exercise[] = [
  { id: 'pull-ups', name: 'Tractions', category: 'pull', canBeWeighted: true },
  { id: 'chin-ups', name: 'Chin-ups', category: 'pull', canBeWeighted: true },
  { id: 'muscle-ups', name: 'Muscle-ups', category: 'pull', canBeWeighted: true },
  { id: 'australian-rows', name: 'Rowings australiens', category: 'pull', canBeWeighted: true },
  { id: 'rowing-barre', name: 'Rowing barre', category: 'pull', canBeWeighted: true },
  { id: 'rowing-haltere', name: 'Rowing haltère', category: 'pull', canBeWeighted: true },
  { id: 'curl-biceps', name: 'Curl biceps', category: 'pull', canBeWeighted: true },
  { id: 'curl-marteau', name: 'Curl marteau', category: 'pull', canBeWeighted: true },
  { id: 'oiseau', name: 'Oiseau', category: 'pull', canBeWeighted: true },
  { id: 'shrugs', name: 'Shrugs', category: 'pull', canBeWeighted: true },
  { id: 'pull-over', name: 'Pull-over', category: 'pull', canBeWeighted: true },
  { id: 'dips', name: 'Dips', category: 'push', canBeWeighted: true },
  { id: 'push-ups', name: 'Pompes', category: 'push', canBeWeighted: true },
  { id: 'diamond-push-ups', name: 'Pompes diamant', category: 'push', canBeWeighted: true },
  { id: 'pike-push-ups', name: 'Pike push-ups', category: 'push', canBeWeighted: true },
  { id: 'handstand-push-ups', name: 'HSPU', category: 'push', canBeWeighted: true },
  { id: 'developpe-couche', name: 'Développé couché', category: 'push', canBeWeighted: true },
  { id: 'developpe-incline', name: 'Développé incliné', category: 'push', canBeWeighted: true },
  { id: 'developpe-decline', name: 'Développé décliné', category: 'push', canBeWeighted: true },
  { id: 'developpe-militaire', name: 'Développé militaire', category: 'push', canBeWeighted: true },
  { id: 'extension-triceps', name: 'Extension triceps', category: 'push', canBeWeighted: true },
  { id: 'barre-au-front', name: 'Barre au front', category: 'push', canBeWeighted: true },
  { id: 'elevations-laterales', name: 'Élévations latérales', category: 'push', canBeWeighted: true },
  { id: 'elevations-frontales', name: 'Élévations frontales', category: 'push', canBeWeighted: true },
  { id: 'pistol-squats', name: 'Pistol squats', category: 'legs', canBeWeighted: true },
  { id: 'squats', name: 'Squats', category: 'legs', canBeWeighted: true },
  { id: 'lunges', name: 'Fentes', category: 'legs', canBeWeighted: true },
  { id: 'calf-raises', name: 'Mollets debout', category: 'legs', canBeWeighted: true },
  { id: 'souleve-de-terre', name: 'Soulevé de terre', category: 'legs', canBeWeighted: true },
  { id: 'souleve-de-terre-roumain', name: 'Soulevé de terre roumain', category: 'legs', canBeWeighted: true },
  { id: 'hip-thrust', name: 'Hip thrust', category: 'legs', canBeWeighted: true },
  { id: 'l-sit', name: 'L-sit', category: 'core', canBeWeighted: true },
  { id: 'leg-raises', name: 'Relevés de jambes', category: 'core', canBeWeighted: true },
  { id: 'dragon-flags', name: 'Dragon flags', category: 'core', canBeWeighted: true },
  { id: 'crunch', name: 'Crunch', category: 'core', canBeWeighted: true },
  { id: 'gainage', name: 'Gainage', category: 'core' },
  { id: 'planche', name: 'Planche', category: 'skill', canBeWeighted: true },
  { id: 'front-lever', name: 'Front lever', category: 'skill', canBeWeighted: true },
  { id: 'back-lever', name: 'Back lever', category: 'skill', canBeWeighted: true },
  { id: 'human-flag', name: 'Human flag', category: 'skill', canBeWeighted: true },
  { id: 'running', name: 'Course', category: 'running' },
  { id: 'sprint', name: 'Sprint', category: 'running' },
  { id: 'interval-run', name: 'Fractionné', category: 'running' },
  { id: 'hill-run', name: 'Course en côte', category: 'running' },
  { id: 'tempo-run', name: 'Tempo run', category: 'running' },
  { id: 'fast-walk', name: 'Marche rapide', category: 'running' },
];

export const CATEGORY_LABELS: Record<Exercise['category'], string> = {
  push: 'Poussée',
  pull: 'Tirage',
  legs: 'Jambes',
  core: 'Abdos',
  skill: 'Skills',
  running: 'Running',
};
